{
 "title": "Application Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "로그량 추이",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "(count_over_time({filename=\"/var/log/app/app.log\"}[$__auto]))"
    }
   ]
  },
  {
   "title": "에러 개수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({filename=\"/var/log/app/app.log\", level=\"ERROR\"}[$__range]))"
    }
   ]
  },
  {
   "title": "실시간 로그",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/app/app.log\"}"
    }
   ]
  },
  {
   "title": "ERROR 전용 로그 패널 ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/app/app.log\", level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "로그 레벨 별 비율",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({filename=\"/var/log/app/app.log\"}[$__range]))"
    }
   ]
  }
 ]
}